# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont

from front.component import create_header, create_bottom

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setStyleSheet("QMainWindow{background-color:#d4e2f4}")
        MainWindow.resize(1000, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # self.widget = QtWidgets.QWidget(self.centralwidget)
        # self.widget.setGeometry(QtCore.QRect(0, 0, 1000, 750))
        # self.widget.setObjectName("widget")

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)

        # 垂直方向布局
        self.layout = QtWidgets.QVBoxLayout(self.centralwidget)

        # 返回header组件
        self.header_layout, _, self.btn_return, self.time_show, self.statu_show = create_header('管理员')
        self.layout.addLayout(self.header_layout)

        # main主体
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        # 垂直弹簧
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 1, 1, 1)

        # 水平弹簧
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 6, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 8, 1, 1)

        # 健康评估按钮
        self.health_assess_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.health_assess_Button.sizePolicy().hasHeightForWidth())
        self.health_assess_Button.setSizePolicy(sizePolicy)
        self.health_assess_Button.setBaseSize(QtCore.QSize(0, 0))
        self.health_assess_Button.setObjectName("health_assess_Button")
        self.gridLayout.addWidget(self.health_assess_Button, 1, 1, 1, 1)
        # self.health_assess_Button.setFixedWidth(200)
        # self.health_assess_Button.setFixedHeight(200)
        # self.hlayout1.addWidget(self.health_assess_Button)
        # 结果查看按钮
        self.results_view_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.results_view_Button.sizePolicy().hasHeightForWidth())
        self.results_view_Button.setSizePolicy(sizePolicy)
        self.results_view_Button.setBaseSize(QtCore.QSize(0, 0))
        self.results_view_Button.setObjectName("results_view_Button")
        self.gridLayout.addWidget(self.results_view_Button, 1, 3, 1, 1)
        # self.results_view_Button.setFixedWidth(200)
        # self.results_view_Button.setFixedHeight(200)
        # self.hlayout1.addWidget(self.results_view_Button)

        # self.hlayout2 = QtWidgets.QHBoxLayout(self.centralwidget)
        # 数据查看按钮
        self.data_view_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_view_Button.sizePolicy().hasHeightForWidth())
        self.data_view_Button.setSizePolicy(sizePolicy)
        self.data_view_Button.setBaseSize(QtCore.QSize(0, 0))
        self.data_view_Button.setObjectName("data_view_Button")
        self.gridLayout.addWidget(self.data_view_Button, 1, 5, 1, 1)
        # self.data_view_Button.setFixedWidth(200)
        # self.data_view_Button.setFixedHeight(200)
        # self.hlayout2.addWidget(self.data_view_Button)

        # 模型管理按钮
        self.model_manage_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model_manage_pushButton.sizePolicy().hasHeightForWidth())
        self.model_manage_pushButton.setSizePolicy(sizePolicy)
        self.model_manage_pushButton.setBaseSize(QtCore.QSize(0, 0))
        self.model_manage_pushButton.setObjectName("model_manage_pushButton")
        self.gridLayout.addWidget(self.model_manage_pushButton, 1, 7, 1, 1)
        # self.gridLayout.addWidget(self.model_manage_pushButton, 3, 1, 1, 1)

        # 用户管理按钮
        self.user_manage_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_manage_pushButton.sizePolicy().hasHeightForWidth())
        self.user_manage_pushButton.setSizePolicy(sizePolicy)
        self.user_manage_pushButton.setBaseSize(QtCore.QSize(0, 0))
        self.user_manage_pushButton.setObjectName("model_train_pushButton")
        self.gridLayout.addWidget(self.user_manage_pushButton, 3, 1, 1, 1)
        # self.gridLayout.addWidget(self.user_manage_pushButton, 3, 3, 1, 1)
        
        # 系统参数按钮
        self.parameter_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameter_pushButton.sizePolicy().hasHeightForWidth())
        self.parameter_pushButton.setSizePolicy(sizePolicy)
        self.parameter_pushButton.setBaseSize(QtCore.QSize(0, 0))
        self.parameter_pushButton.setObjectName("parameter_pushButton")
        self.gridLayout.addWidget(self.parameter_pushButton, 3,3,1,1)
        # 日志管理按钮
        self.log_manage_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_manage_pushButton.sizePolicy().hasHeightForWidth())
        self.log_manage_pushButton.setSizePolicy(sizePolicy)
        self.log_manage_pushButton.setBaseSize(QtCore.QSize(0, 0))
        self.log_manage_pushButton.setObjectName("log_manage_pushButton")
        self.gridLayout.addWidget(self.log_manage_pushButton,3,5,1,1 )
        # 密码修改按钮
        self.change_pwd_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change_pwd_Button.sizePolicy().hasHeightForWidth())
        self.change_pwd_Button.setSizePolicy(sizePolicy)
        self.change_pwd_Button.setBaseSize(QtCore.QSize(0, 0))
        self.change_pwd_Button.setObjectName("change_pwd_Button")
        self.gridLayout.addWidget(self.change_pwd_Button, 3, 7, 1, 1)
        # self.gridLayout.addWidget(self.change_pwd_Button, 3, 5, 1, 1)

        # self.admin_login_Button.setFixedWidth(200)
        # self.admin_login_Button.setFixedHeight(200)
        # self.hlayout2.addWidget(self.admin_login_Button)
        MainWindow.setCentralWidget(self.centralwidget)

        # self.layout.addLayout(self.hlayout1)  # 将主体加入布局
        # self.layout.addLayout(self.hlayout2)  # 将主体加入布局
        self.layout.addLayout(self.gridLayout)
        # self.layout.addStretch(1)

        # 返回footer组件
        self.bottom_layout, self.evaluate_time, self.pass_time = create_bottom()
        self.layout.addLayout(self.bottom_layout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "应激系统"))
        self.data_view_Button.setText(_translate("MainWindow", "数据\n查看"))
        self.health_assess_Button.setText(_translate("MainWindow", "应激\n评估"))
        self.parameter_pushButton.setText(_translate("MainWindow", "系统\n参数"))
        self.results_view_Button.setText(_translate("MainWindow", "结果\n查看"))
        self.change_pwd_Button.setText(_translate("MainWindow", "密码\n修改"))
        self.model_manage_pushButton.setText(_translate("MainWindow", "模型\n管理"))
        self.user_manage_pushButton.setText(_translate("MainWindow", "用户\n管理"))
        self.log_manage_pushButton.setText(_translate("MainWindow", "日志\n管理"))

        font = QFont()
        font.setFamily("Microsoft YaHei")
        self.data_view_Button.setFont(font)
        self.health_assess_Button.setFont(font)
        self.parameter_pushButton.setFont(font)
        self.results_view_Button.setFont(font)
        self.change_pwd_Button.setFont(font)
        self.model_manage_pushButton.setFont(font)
        self.user_manage_pushButton.setFont(font)
        self.log_manage_pushButton.setFont(font)

        # 样式设置      "QPushButton{font-weight:bold}"字体加粗
        self.health_assess_Button.setStyleSheet("QPushButton{color:white}"
                                                "QPushButton:hover{background-color:#94b2da}"
                                                "QPushButton{background-color:#4379b9}"
                                                "QPushButton{border:2px}"
                                                "QPushButton{border-radius:10px}"
                                                "QPushButton{padding:2px 4px}"
                                                "QPushButton{font-size:30px}")
        self.results_view_Button.setStyleSheet("QPushButton{color:white}"
                                                "QPushButton:hover{background-color:#94b2da}"
                                                "QPushButton{background-color:#4379b9}"
                                                "QPushButton{border:2px}"
                                                "QPushButton{border-radius:10px}"
                                                "QPushButton{padding:2px 4px}"
                                                "QPushButton{font-size:30px}")
        self.data_view_Button.setStyleSheet("QPushButton{color:white}"
                                                "QPushButton:hover{background-color:#94b2da}"
                                                "QPushButton{background-color:#4379b9}"
                                                "QPushButton{border:2px}"
                                                "QPushButton{border-radius:10px}"
                                                "QPushButton{padding:2px 4px}"
                                                "QPushButton{font-size:30px}")
        self.model_manage_pushButton.setStyleSheet("QPushButton{color:white}"
                                                "QPushButton:hover{background-color:#94b2da}"
                                                "QPushButton{background-color:#4379b9}"
                                                "QPushButton{border:2px}"
                                                "QPushButton{border-radius:10px}"
                                                "QPushButton{padding:2px 4px}"
                                                "QPushButton{font-size:30px}")
        self.user_manage_pushButton.setStyleSheet("QPushButton{color:white}"
                                              "QPushButton:hover{background-color:#94b2da}"
                                              "QPushButton{background-color:#4379b9}"
                                              "QPushButton{border:2px}"
                                              "QPushButton{border-radius:10px}"
                                              "QPushButton{padding:2px 4px}"
                                              "QPushButton{font-size:30px}")
        self.parameter_pushButton.setStyleSheet("QPushButton{color:white}"
                                              "QPushButton:hover{background-color:#94b2da}"
                                              "QPushButton{background-color:#4379b9}"
                                              "QPushButton{border:2px}"
                                              "QPushButton{border-radius:10px}"
                                              "QPushButton{padding:2px 4px}"
                                              "QPushButton{font-size:30px}")
        self.log_manage_pushButton.setStyleSheet("QPushButton{color:white}"
                                              "QPushButton:hover{background-color:#94b2da}"
                                              "QPushButton{background-color:#4379b9}"
                                              "QPushButton{border:2px}"
                                              "QPushButton{border-radius:10px}"
                                              "QPushButton{padding:2px 4px}"
                                              "QPushButton{font-size:30px}")
        self.change_pwd_Button.setStyleSheet("QPushButton{color:white}"
                                              "QPushButton:hover{background-color:#94b2da}"
                                              "QPushButton{background-color:#4379b9}"
                                              "QPushButton{border:2px}"
                                              "QPushButton{border-radius:10px}"
                                              "QPushButton{padding:2px 4px}"
                                              "QPushButton{font-size:30px}")

