# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QFont

from front.component import create_header, create_bottom

# index.py
# 主页面的实现
# 包含应激评估、结果查看、数据查看功能
# 使用PyQt5创建图形用户界面

# 主要功能：
# 1. 创建主窗口布局
# 2. 设置应激评估、结果查看、数据查看按钮
# 3. 设置页面样式和字体

class Ui_MainWindow(object):
    """
    主窗口UI类
    
    负责创建和设置主窗口的所有UI元素
    """

    def setupUi(self, MainWindow):
        """
        设置主窗口UI
        
        参数:
        MainWindow (QMainWindow): 主窗口对象
        
        功能:
        - 设置窗口基本属性（标题、大小、样式）
        - 创建并设置中央窗口部件
        - 设置布局（垂直布局）
        - 添加页面头部
        - 创建并添加主体网格布局
        - 添加各个功能按钮（应激评估、结果查看、数据查看、密码修改）
        - 添加页面底部
        - 设置样式和字体
        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.setStyleSheet("QMainWindow{background-color:#d4e2f4}")
        MainWindow.resize(1000, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # 垂直方向布局
        self.layout = QtWidgets.QVBoxLayout(self.centralwidget)

        # 返回header组件
        self.header_layout, _, self.btn_return, _, self.btn_help = create_header('普通用户', show_help=True)
        self.layout.addLayout(self.header_layout)

        # main主体
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        # 垂直弹簧
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 4, 1, 1, 1)
        # 水平弹簧
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 5, 1, 1)
        # 健康评估按钮
        self.health_assess_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.health_assess_Button.sizePolicy().hasHeightForWidth())
        self.health_assess_Button.setSizePolicy(sizePolicy)
        self.health_assess_Button.setObjectName("health_assess_Button")
        self.gridLayout.addWidget(self.health_assess_Button, 1, 1, 1, 1)

        # 结果查看按钮
        self.results_view_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.results_view_Button.sizePolicy().hasHeightForWidth())
        self.results_view_Button.setSizePolicy(sizePolicy)
        self.results_view_Button.setObjectName("results_view_Button")
        self.gridLayout.addWidget(self.results_view_Button, 1, 4, 1, 1)

        # 数据查看按钮
        self.data_view_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_view_Button.sizePolicy().hasHeightForWidth())
        self.data_view_Button.setSizePolicy(sizePolicy)
        self.data_view_Button.setObjectName("data_view_Button")
        self.gridLayout.addWidget(self.data_view_Button, 3, 1, 1, 1)

        # 密码修改按钮
        self.change_pwd_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change_pwd_Button.sizePolicy().hasHeightForWidth())
        self.change_pwd_Button.setSizePolicy(sizePolicy)
        self.change_pwd_Button.setObjectName("change_pwd_Button")
        self.gridLayout.addWidget(self.change_pwd_Button, 3, 4, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)

        self.layout.addLayout(self.gridLayout)

        # 返回footer组件
        self.bottom_layout, self.evaluate_time, self.pass_time = create_bottom()
        self.layout.addLayout(self.bottom_layout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        """
        重新翻译UI
        
        参数:
        MainWindow (QMainWindow): 主窗口对象
        
        功能:
        - 设置窗口标题
        - 设置按钮文本
        - 设置字体
        - 设置按钮样式
        """
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "长远航作业应激神经系统功能预警评估系统"))
        self.health_assess_Button.setText(_translate("MainWindow", "应激\n评估"))
        self.results_view_Button.setText(_translate("MainWindow", "结果\n管理"))
        self.data_view_Button.setText(_translate("MainWindow", "数据\n管理"))
        self.change_pwd_Button.setText(_translate("MainWindow", "密码\n修改"))

        font = QFont()
        font.setFamily("Microsoft YaHei")  # 微软雅黑
        self.health_assess_Button.setFont(font)
        self.results_view_Button.setFont(font)
        self.data_view_Button.setFont(font)
        self.change_pwd_Button.setFont(font)

        # 样式设置      "QPushButton{font-weight:bold}"字体加粗
        button_style = ("QPushButton{color:white}"
                       "QPushButton:hover{background-color:#94b2da}"
                       "QPushButton{background-color:#4379b9}"
                       "QPushButton{border:2px}"
                       "QPushButton{border-radius:10px}"
                       "QPushButton{padding:2px 4px}"
                       "QPushButton{font-size:30px}")

        self.health_assess_Button.setStyleSheet(button_style)
        self.results_view_Button.setStyleSheet(button_style)
        self.data_view_Button.setStyleSheet(button_style)
        self.change_pwd_Button.setStyleSheet(button_style)


