# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'health_evaluate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QTableWidgetItem

from front.component import create_header, create_bottom
from sql_model.tb_result import Result
from util.db_util import SessionClass


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 750)
        MainWindow.setStyleSheet("QMainWindow{background-color:#d4e2f4}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # 垂直方向布局
        self.layout = QtWidgets.QVBoxLayout(self.centralwidget)

        # 返回header组件
        self.header_layout, _, self.btn_return, _,_ = create_header('健康状态分析')
        self.layout.addLayout(self.header_layout)

        # main主体
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")

        # 表格
        self.lst= ['ID', '人员id', '数据路径','上传用户','操作']
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setStyleSheet("margin-right:15px")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(len(self.lst))
        self.tableWidget.setHorizontalHeaderLabels(self.lst)
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)  # 使列表自适应宽度
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)  # 设置tablewidget不可编辑
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)  # 设置tablewidget不可选中
        self.tableWidget.resizeColumnsToContents()  # 设置列宽高按照内容自适应
        self.gridLayout_2.addWidget(self.tableWidget, 1, 0, 2, 4)

        # 可视化板块
        self.curve = QtWidgets.QWidget(self.centralwidget)  # 内嵌窗口
        self.curve.setStyleSheet("background-color: #5c8ac3;border-radius:20px")
        self.curve.setObjectName("curve")
        self.curve_layout = QtWidgets.QVBoxLayout(self.curve)
        self.curve_label = QtWidgets.QLabel(self.curve)
        self.curve_label.setText("数据可视")
        self.curve_label.setStyleSheet("Text-align: center;font-size:25px;")
        self.curve_label.setAlignment(QtCore.Qt.AlignCenter)
        self.curve_layout.addWidget(self.curve_label)
        self.curve_graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.curve_graphicsView.setObjectName("curve_graphicsView")
        self.curve_layout.addWidget(self.curve_graphicsView)

        # 添加一个水平布局
        self.button_layout = QtWidgets.QHBoxLayout()
        self.curve_layout.addLayout(self.button_layout)

        # 在水平布局中添加两个按钮
        self.pushButton = QtWidgets.QPushButton(self.curve)
        self.pushButton.setObjectName("prevButton")
        self.button_layout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.curve)
        self.pushButton_2.setObjectName("nextButton")
        self.button_layout.addWidget(self.pushButton_2)
        self.pushButton.setStyleSheet("background-color: white;")
        self.pushButton_2.setStyleSheet("background-color: white; ")

        self.gridLayout_2.addWidget(self.curve, 2, 4, 1, 1)
        # self.curve_graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        # self.curve_graphicsView.setObjectName("curve_graphicsView")
        # self.gridLayout_2.addWidget(self.curve_graphicsView, 1, 4, 1, 1)

        # 垂直布局,包含三种状态的Widget和剩余寿命的Widget
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        # 三种状态的Widget
        self.classifer = QtWidgets.QWidget(self.centralwidget)  # 内嵌窗口
        self.classifer.setStyleSheet("background-color: #5c8ac3;border-radius:20px")
        self.classifer.setObjectName("classifer")
        self.gridLayout = QtWidgets.QGridLayout(self.classifer)
        self.gridLayout.setObjectName("gridLayout")
        # # 健康状态(平稳运行阶段)
        # self.health_led_label = QtWidgets.QLabel(self.classifer)
        # self.health_led_label.setStyleSheet(
        #     "min-width: 30px; min-height: 30px;max-width:30px; max-height: 30px;border-radius: 16px; border:2px solid white;background:white")
        # self.health_led_label.setText("")
        # self.health_led_label.setObjectName("health_led_label")
        # self.gridLayout.addWidget(self.health_led_label, 0, 0, 1, 1)
        # self.health_label = QtWidgets.QLabel(self.classifer)
        # self.health_label.setObjectName("health_label")
        # self.gridLayout.addWidget(self.health_label, 0, 1, 1, 1)

        # 普通应激
        self.ordinarystress_led_label = QtWidgets.QLabel(self.classifer)
        self.ordinarystress_led_label.setStyleSheet(
            "min-width: 30px; min-height: 30px;max-width:30px; max-height: 30px;border-radius: 16px; border:2px solid white;background:white")
        self.ordinarystress_led_label.setText("")
        self.ordinarystress_led_label.setObjectName("ordinarystress_led_label")
        self.gridLayout.addWidget(self.ordinarystress_led_label, 0, 0, 1, 1)
        self.ordinarystress_label = QtWidgets.QLabel(self.classifer)
        self.ordinarystress_label.setObjectName("ordinarystress_label")
        self.gridLayout.addWidget(self.ordinarystress_label, 0, 1, 1, 1)
        # 抑郁
        self.depression_led_label = QtWidgets.QLabel(self.classifer)
        self.depression_led_label.setStyleSheet(
            "min-width: 30px; min-height: 30px;max-width:30px; max-height: 30px;border-radius: 16px; border:2px solid white;background:white")
        self.depression_led_label.setText("")
        self.depression_led_label.setObjectName("depression_led_label")
        self.gridLayout.addWidget(self.depression_led_label, 1, 0, 1, 1)
        self.depression_label = QtWidgets.QLabel(self.classifer)
        self.depression_label.setObjectName("depression_label")
        self.gridLayout.addWidget(self.depression_label, 1, 1, 1, 1)
        # 焦虑
        self.anxiety_led_label = QtWidgets.QLabel(self.classifer)
        self.anxiety_led_label.setStyleSheet(
            "min-width: 30px; min-height: 30px;max-width:30px; max-height: 30px;border-radius: 16px; border:2px solid white;background:white")

        self.anxiety_led_label.setText("")
        self.anxiety_led_label.setObjectName("anxiety_led_label")
        self.gridLayout.addWidget(self.anxiety_led_label, 2, 0, 1, 1)
        self.anxiety_label = QtWidgets.QLabel(self.classifer)
        self.anxiety_label.setObjectName("anxiety_label")
        self.gridLayout.addWidget(self.anxiety_label, 2, 1, 1, 1)

        self.verticalLayout.addWidget(self.classifer)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)

        self.status_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_label.sizePolicy().hasHeightForWidth())
        self.status_label.setSizePolicy(sizePolicy)
        self.status_label.setStyleSheet("background-color: #8caed6;"
                                        "Text-align: center;"
                                        "margin:10px,auto,20px,20px;"
                                        "border-radius:20px;"
                                        "font-size:40px;color: black;font-family: 宋体")
        self.status_label.setTextFormat(QtCore.Qt.AutoText)
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.gridLayout_2.addWidget(self.status_label, 0, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.layout.addLayout(self.gridLayout_2)  # 把主体部分加入垂直布局

        # 返回footer组件
        self.bottom_layout, self.evaluate_time, self.pass_time = create_bottom()
        self.layout.addLayout(self.bottom_layout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "应激评估系统"))
        MainWindow.setStyleSheet("QMainWindow{background-color:#d4e2f4}")

        self.ordinarystress_label.setText(_translate("MainWindow", "普通应激"))
        self.depression_label.setText(_translate("MainWindow", "抑郁"))
        self.anxiety_label.setText(_translate("MainWindow", "焦虑"))

        self.pushButton.setText(_translate("MainWindow", "Prev"))
        self.pushButton_2.setText(_translate("MainWindow", "Next"))


        font = QFont()
        font.setFamily("Microsoft YaHei")  # 微软雅黑
        self.status_label.setFont(font)
        self.tableWidget.setFont(font)
        # self.life_time.setFont(font)
        self.ordinarystress_label.setFont(font)
        self.depression_label.setFont(font)
        self.anxiety_label.setFont(font)
        # self.mechanical_label.setFont(font)
        # self.life_label.setFont(font)
        self.curve_label.setFont(font)

        self.depression_label.setStyleSheet("font-size:25px;color:black")
        self.ordinarystress_label.setStyleSheet("font-size:25px")
        self.anxiety_label.setStyleSheet("font-size:25px")

        # self.mechanical_label.setStyleSheet("font-size:25px")
        # self.life_label.setStyleSheet("font-size:25px;color:black")
        # self.life_time.setStyleSheet("color:black;font-size:18px;")

        # 表属性样式设计

        self.tableWidget.horizontalHeader().setStyleSheet(
            "QHeaderView::section{background-color:#5c8ac3;font-size:11pt;color: black;};")
        self.tableWidget.setStyleSheet("background-color:#d4e2f4; color:black; border:1px solid #5c8ac3")
