# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont

from front.component import create_header, create_bottom


class Ui_MainWindow(object):
    """
    数据查看界面UI类
    
    负责创建和设置数据查看界面的所有UI元素
    """

    def setupUi(self, MainWindow):
        """
        设置数据查看界面UI
        
        参数:
        MainWindow (QMainWindow): 主窗口对象
        
        功能:
        - 设置窗口基本属性（标题、大小、样式）
        - 创建并设置中央窗口部件
        - 设置布局（垂直布局）
        - 添加页面头部
        - 创建并添加数据表格
        - 创建并添加上传按钮
        - 创建并添加可视化指标选择下拉框
        - 创建并添加数据可视化区域
        - 设置样式和字体
        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 750)
        MainWindow.setStyleSheet("QMainWindow{background-color:#d4e2f4}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # self.widget = QtWidgets.QWidget(self.centralwidget)
        # self.widget.setGeometry(QtCore.QRect(170, 90, 471, 401))
        # self.widget.setObjectName("widget")
        # 垂直方向布局
        self.layout = QtWidgets.QVBoxLayout(self.centralwidget)

        # 返回header组件
        self.header_layout, _, self.btn_return, self.time_show, self.statu_show = create_header('数据查看')
        self.layout.addLayout(self.header_layout)

        # main主体
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        # 表格
        self.lst = ['ID', '人员id', '姓名', '文件路径', '上传用户', '上传时间', '操作']
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(len(self.lst))
        self.tableWidget.setHorizontalHeaderLabels(self.lst)
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)  # 使列表自适应宽度
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)  # 设置tablewidget不可编辑
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)  # 设置tablewidget不可选中

        self.tableWidget.resizeColumnsToContents()  # 设置列宽高按照内容自适应
        # 设置特定列的宽度
        self.tableWidget.setColumnWidth(0, 50)  # 第一列（ID）
        self.tableWidget.setColumnWidth(1, 50)  # 第二列（人员id）
        self.tableWidget.setColumnWidth(3, 200)  # 第四列（文件路径）
        self.tableWidget.setColumnWidth(5, 150)  # 为上传时间列设置合适的宽度

        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 2)
        # 创建一个垂直布局来放置右侧的按钮
        self.button_layout = QtWidgets.QVBoxLayout()
        self.button_layout.setSpacing(10)  # 设置按钮之间的间距
        self.button_layout.setContentsMargins(10, 30, 10, 10)  # 设置上下左右边距
        
        # 添加上传按钮
        self.upload_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.upload_pushButton.setFixedSize(120, 50)
        self.upload_pushButton.setStyleSheet("background-color: #759dcd;font-size: 18px;border-radius:12px")
        self.upload_pushButton.setObjectName("load_pushButton")
        self.button_layout.addWidget(self.upload_pushButton)
        
        # 添加批量上传按钮
        self.batch_upload_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.batch_upload_pushButton.setFixedSize(120, 50)
        self.batch_upload_pushButton.setStyleSheet("background-color: #759dcd;font-size: 18px;border-radius:12px")
        self.batch_upload_pushButton.setObjectName("batch_upload_pushButton")
        self.button_layout.addWidget(self.batch_upload_pushButton)

        # 添加选择前200条按钮
        self.select_top_200_button = QtWidgets.QPushButton(self.centralwidget)
        self.select_top_200_button.setFixedSize(120, 50)
        self.select_top_200_button.setStyleSheet("background-color: #759dcd;font-size: 18px;border-radius:12px")
        self.select_top_200_button.setObjectName("select_top_200_button")
        self.button_layout.addWidget(self.select_top_200_button)

        # 添加批量预处理按钮
        self.batch_preprocess_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.batch_preprocess_pushButton.setFixedSize(120, 50)
        self.batch_preprocess_pushButton.setStyleSheet("background-color: #759dcd;font-size: 18px;border-radius:12px")
        self.batch_preprocess_pushButton.setObjectName("batch_preprocess_pushButton")
        self.button_layout.addWidget(self.batch_preprocess_pushButton)

        # 添加选择数量显示标签
        self.selection_count_label = QtWidgets.QLabel(self.centralwidget)
        self.selection_count_label.setStyleSheet("font-size: 14px; color: #333; margin-top: 10px;")
        self.selection_count_label.setAlignment(QtCore.Qt.AlignCenter)
        self.button_layout.addWidget(self.selection_count_label)

        # 添加弹簧，使按钮靠上对齐
        self.button_layout.addStretch()

        # 创建一个widget来容纳按钮布局
        button_container = QtWidgets.QWidget()
        button_container.setLayout(self.button_layout)
        self.gridLayout.addWidget(button_container, 0, 2, 2, 1)

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        # 添加顶部的spacerItem，增加高度
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.horizontalLayout = QtWidgets.QVBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        # 下拉框标签
        self.channel_choice_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channel_choice_label.sizePolicy().hasHeightForWidth())
        self.channel_choice_label.setSizePolicy(sizePolicy)
        self.channel_choice_label.setAlignment(QtCore.Qt.AlignCenter)
        self.channel_choice_label.setObjectName("channel_choice_label")
        self.horizontalLayout.addWidget(self.channel_choice_label)
        # 下拉框
        self.channel_comboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channel_comboBox.sizePolicy().hasHeightForWidth())
        self.channel_comboBox.setSizePolicy(sizePolicy)
        self.channel_comboBox.setObjectName("channel_comboBox")
        self.channel_comboBox.addItem("0")
        self.channel_comboBox.addItem("1")
        self.channel_comboBox.addItem("2")
        self.channel_comboBox.addItem("3")
        self.channel_comboBox.addItem("4")

        self.horizontalLayout.addWidget(self.channel_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        # 添加底部的spacerItem，增加高度
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        # 压力曲线widget
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("background-color: #5c8ac3;border-radius:20px")
        self.widget_2.setObjectName("widget_2")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pressure_curve_label = QtWidgets.QLabel(self.widget_2)
        self.pressure_curve_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pressure_curve_label.setStyleSheet("font-size:25px")
        self.pressure_curve_label.setObjectName("pressure_curve_label")
        self.verticalLayout_3.addWidget(self.pressure_curve_label)

        self.graphicsView = QtWidgets.QGraphicsView(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_3.addWidget(self.graphicsView)
        self.gridLayout.addWidget(self.widget_2, 1, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.layout.addLayout(self.gridLayout)  # 把主体部分加入垂直布局

        # 返回footer组件
        self.bottom_layout, self.evaluate_time, self.pass_time = create_bottom()
        # self.layout.addLayout(self.bottom_layout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        """
        重新翻译UI
        
        参数:
        MainWindow (QMainWindow): 主窗口对象
        
        功能:
        - 设置窗口标题
        - 设置各个标签和按钮的文本
        - 设置下拉框选项
        - 设置字体
        - 设置样式
        """
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "长远航作业应激神经系统功能预警评估系统"))
        MainWindow.setStyleSheet("QMainWindow{background-color:#d4e2f4}")

        self.upload_pushButton.setText(_translate("MainWindow", "上传"))
        self.channel_choice_label.setText(_translate("MainWindow", "可视化指标选择："))
        self.channel_comboBox.setItemText(0, _translate("MainWindow", "differential_entropy"))
        self.channel_comboBox.setItemText(1, _translate("MainWindow", "frequency_domain_features"))
        self.channel_comboBox.setItemText(2, _translate("MainWindow", "theta_alpha_beta_gamma_powers"))
        self.channel_comboBox.setItemText(3, _translate("MainWindow", "time_domain_features"))
        self.channel_comboBox.setItemText(4, _translate("MainWindow", "time_frequency_features"))

        self.pressure_curve_label.setText(_translate("MainWindow", "数据可视"))

        font = QFont()
        font.setFamily("Microsoft YaHei")  # 微软雅黑
        font.setPointSize(10)  # 调整字体大小
        self.tableWidget.setFont(font)
        self.upload_pushButton.setFont(font)
        self.channel_choice_label.setFont(font)
        self.channel_comboBox.setFont(font)
        # self.data_export_pushButton.setFont(font)
        self.pressure_curve_label.setFont(font)

        self.channel_choice_label.setStyleSheet("font-size:25px")
        self.channel_comboBox.setStyleSheet("font-size:25px;padding-left:20px;padding-top:10px;padding-bottom:10px;"
                                            "border-radius:8px;border:2px solid #316eb5")
        self.tableWidget.horizontalHeader().setStyleSheet(
            "QHeaderView::section{background-color:#5c8ac3;font-size:11pt;color: black;};")
        self.tableWidget.setStyleSheet("background-color:#d4e2f4; color:black; border:1px solid #5c8ac3")
        self.batch_upload_pushButton.setText(_translate("MainWindow", "批量上传"))
        self.batch_upload_pushButton.setFont(font)
        self.batch_preprocess_pushButton.setText(_translate("MainWindow", "批量预处理"))
        self.batch_preprocess_pushButton.setFont(font)
        self.select_top_200_button.setText(_translate("MainWindow", "选择前200条"))
        self.selection_count_label.setText(_translate("MainWindow", "已选择: 0/200"))

