# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'results_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import (
    QMainWindow, QWidget, QVBoxLayout, QHBoxLayout, 
    QLabel, QLineEdit, QPushButton, QComboBox,
    QTableWidget, QTableWidgetItem, QHeaderView
)

from front.component import create_header, create_bottom


class Ui_MainWindow(object):
    """
    用户管理界面UI类
    
    负责创建和设置用户管理界面的所有UI元素
    """

    def setupUi(self, MainWindow):
        """
        设置用户管理界面UI
        
        参数:
        MainWindow (QMainWindow): 主窗口对象
        
        功能:
        - 设置窗口基本属性（标题、大小、样式）
        - 创建并设置中央窗口部件
        - 设置布局（垂直布局）
        - 添加页面头部
        - 创建并添加用户列表表格
        - 创建并添加用户添加表单
        - 设置样式和字体
        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 750)
        MainWindow.setStyleSheet("QMainWindow{background-color:#d4e2f4}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # 垂直方向布局
        self.layout = QtWidgets.QVBoxLayout(self.centralwidget)

        # 返回header组件
        self.header_layout, _, self.btn_return, self.time_show, self.statu_show = create_header('用户管理界面')
        self.layout.addLayout(self.header_layout)

        self.mainVLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainVLayout.setObjectName("mainVLayout")
        self.layout.addLayout(self.mainVLayout)

        # 修改表格列
        self.lst = ['ID', '用户名', '角色', '邮箱', '电话', '操作']
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setStyleSheet("margin-right:15px")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(len(self.lst))
        self.tableWidget.setHorizontalHeaderLabels(self.lst)
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.resizeColumnsToContents()
        self.mainVLayout.addWidget(self.tableWidget)

        self.hLayout = QtWidgets.QHBoxLayout()
        self.hLayout.setObjectName("hLayout")
        self.mainVLayout.addLayout(self.hLayout)

        # 创建左边弹簧
        left_spacer = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout.addItem(left_spacer)

        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.hLayout.addLayout(self.gridLayout)

        # 用户名
        self.nameLabel = QtWidgets.QLabel("用户名：", self.centralwidget)
        self.nameIN = QtWidgets.QLineEdit(self.centralwidget)
        self.gridLayout.addWidget(self.nameLabel, 0, 0)
        self.gridLayout.addWidget(self.nameIN, 0, 1)
        
        # 密码
        self.pswdLabel = QtWidgets.QLabel("密码：", self.centralwidget)
        self.pswdIN = QtWidgets.QLineEdit(self.centralwidget)
        self.pswdIN.setEchoMode(QtWidgets.QLineEdit.Password)
        self.gridLayout.addWidget(self.pswdLabel, 1, 0)
        self.gridLayout.addWidget(self.pswdIN, 1, 1)
        
        # 邮箱
        self.emailLabel = QtWidgets.QLabel("邮箱：", self.centralwidget)
        self.emailIN = QtWidgets.QLineEdit(self.centralwidget)
        self.gridLayout.addWidget(self.emailLabel, 0, 2)
        self.gridLayout.addWidget(self.emailIN, 0, 3)
        
        # 电话
        self.phoneLabel = QtWidgets.QLabel("电话：", self.centralwidget)
        self.phoneIN = QtWidgets.QLineEdit(self.centralwidget)
        self.gridLayout.addWidget(self.phoneLabel, 1, 2)
        self.gridLayout.addWidget(self.phoneIN, 1, 3)
        
        # 角色选择
        self.characterLabel = QtWidgets.QLabel("角色：", self.centralwidget)
        self.character_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.character_comboBox.addItem("普通用户")
        self.character_comboBox.addItem("管理员")
        self.gridLayout.addWidget(self.characterLabel, 2, 0)
        self.gridLayout.addWidget(self.character_comboBox, 2, 1)

        # 上传按钮
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setFixedSize(100, 50)  # 设置固定尺寸
        self.addButton.setStyleSheet("margin-top:10px;margin-bottom:10px;margin-left:10px;\n"
                                     "background-color: #759dcd;font-size: 18px;border-radius:10px")  # 调整样式
        self.addButton.setCheckable(False)
        self.addButton.setObjectName("addButton")
        self.hLayout.addWidget(self.addButton)

        # 创建右边弹簧
        right_spacer = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout.addItem(right_spacer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        """
        重新翻译UI
        
        参数:
        MainWindow (QMainWindow): 主窗口对象
        
        功能:
        - 设置窗口标题
        - 设置各个标签和按钮的文本
        - 设置字体
        - 设置样式
        """
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "长远航作业应激神经系统功能预警评估系统"))
        self.nameLabel.setText(_translate("MainWindow", "用户名："))
        self.pswdLabel.setText(_translate("MainWindow", "密码："))
        self.characterLabel.setText(_translate("MainWindow", "角色："))

        font = QFont()
        font.setFamily("Microsoft YaHei")  # 微软雅黑
        self.nameLabel.setFont(font)
        self.pswdLabel.setFont(font)
        self.characterLabel.setFont(font)
        self.character_comboBox.setFont(font)

        self.nameIN.setFont(font)
        self.pswdIN.setFont(font)

        self.nameLabel.setStyleSheet("font-size:20px")
        self.pswdLabel.setStyleSheet("font-size:20px")
        self.characterLabel.setStyleSheet("font-size:20px")
        self.character_comboBox.setStyleSheet("font-size:16px")
        self.nameIN.setStyleSheet("font-size:16px")
        self.pswdIN.setStyleSheet("font-size:16px")

        self.addButton.setText(_translate("MainWindow", "添加"))

        self.tableWidget.horizontalHeader().setStyleSheet(
            "QHeaderView::section{background-color:#5c8ac3;font-size:11pt;color: black;};")
        self.tableWidget.setStyleSheet("background-color:#d4e2f4; color:black; border:1px solid #5c8ac3")

